name: build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    env: 
      COVERALLS_TOKEN: ${{ secrets.COVERALLS_TOKEN }}
    steps:
      - name: checkout
        uses: actions/checkout@v3.5.2
        
      - name: Setup Java JDK
        uses: actions/setup-java@v1.4.4
        with:
          java-version: 8
          
      - name: build
        run: mvn package
